export enum Role {
    ADMIN = 'ADMIN',
    PRODUCTEUR = 'PRODUCTEUR',
    SYNDICAT_AOP = 'SYNDICAT_AOP',
    PARTENAIRE_PTF2A = 'PARTENAIRE_PTF2A',
    TECHNICIEN_IPREM = 'TECHNICIEN_IPREM',
    INGENIEUR_IPREM = 'INGENIEUR_IPREM',
    CHEF_PROJET_IPREM = 'CHEF_PROJET_IPREM',
  }
  